FROM golang:1.14 as builder

WORKDIR /go/src/app

RUN go get -d -v ./...
RUN go install -v ./...

COPY . . 

RUN go build -ldflags "-s -w" hello.go


FROM scratch
COPY --from=builder /go/src/app/hello .
ENTRYPOINT [ "./hello" ]
